#!/usr/bin/env bash
# =============================================================================
#  Module 1 : Cell-type-specific interaction eQTL (ieQTL) mapping (tensorQTL)
# =============================================================================
#
#  Description
#  -----------
#  Maps cell-type-specific interaction eQTLs (ieQTLs) within a single tissue.
#  For every cell type of that tissue, tensorQTL fits the cis-nominal
#  interaction model
#
#      expression ~ genotype + cell_type_proportion
#                   + genotype x cell_type_proportion
#
#  for all variants inside the cis-window (tensorQTL default: +/- 1 Mb around
#  the TSS) of every gene. The genotype x cell-type-proportion interaction term
#  defines an ieQTL, i.e. a variant whose effect on expression depends on the
#  cell-type composition of the bulk tissue sample.
#
#  The script is written to be submitted as an HPC array job: the tissue is
#  selected by a 0-based index given as the first command-line argument, so one
#  array task processes one tissue and loops over all of its cell types.
#
#  Usage
#  -----
#      bash run_tensorqtl_interaction.sh <TISSUE_INDEX>      # 0-based, 0..33
#
#      # process "Blood" (index 4)
#      bash run_tensorqtl_interaction.sh 4
#
#      # SGE array job: one task per tissue
#      qsub -t 0-33 -cwd -pe smp 8 run_tensorqtl_interaction.sh $SGE_TASK_ID
#
#      # SLURM array job: one task per tissue
#      #   sbatch --array=0-33 ...
#      #   inside the SLURM script: bash run_tensorqtl_interaction.sh $SLURM_ARRAY_TASK_ID
#
#  Dependencies
#  ------------
#      tensorQTL   pip install tensorqtl        (Python 3)
#      PLINK 2     one pgen/pvar/psam (or bed/bim/fam) genotype set per tissue
#
#  Required inputs (paths are set in the configuration block below)
#  ---------------------------------------------------------------
#      * Expression phenotypes in BED format (TMM-normalised, inverse-normal
#        transformed), one column per sample.
#      * Covariates file (covariates x samples, tab-delimited, with headers).
#      * Interaction-term file (samples x one cell-type-proportion column).
#      * PLINK genotype prefix filtered to MAF >= 0.05 and MAC >= 6.
#
#  Output
#  ------
#  With --best_only, tensorQTL writes only the top association per phenotype
#  together with its eigenMT-adjusted statistics:
#
#      ${DIR_OUTPUT}/${tissue}/${tissue}.interactions_${celltype}.cis_qtl_top_assoc.txt.gz
#
#  Columns used downstream for ieQTL calling:
#      pval_gi       interaction p-value (genotype x cell-type proportion)
#      pval_emt      eigenMT-adjusted p-value (pval_gi * effective number of tests)
#      pval_adj_bh   Benjamini-Hochberg adjusted p-value
#
#  IMPORTANT
#  ---------
#  `--best_only` DISABLES the full per-variant summary statistics. Those full
#  statistics (one row per variant-gene pair) are required by the colocalisation
#  step in Module 2 and must be generated by re-running the very same command
#  WITHOUT `--best_only`. See the top-level README ("Reproducibility notes").
#
#  Notes
#  -----
#  Cell types are processed sequentially; the original analysis used the same
#  sequential structure. Increase throughput by submitting more array tasks, or
#  parallelise the inner cell-type loop with GNU parallel / xargs -P.
# =============================================================================

set -uo pipefail

# -----------------------------------------------------------------------------
# USER CONFIGURATION - edit every path below before running
# -----------------------------------------------------------------------------

# Root directory of this module; all relative paths below are resolved from here.
WORK_DIR="/path/to/Pig_GTEx_ISU_immuneCell/celltype_interaction"

# Directory holding the interaction-term files, named
#     ${tissue}.interactions_${celltype}.txt
DIR_INTERACTION="interaction_term_celltype"

# Expression phenotypes (TMM + inverse-normal transformed), in BED format.
DIR_EXPRESSION="/path/to/Pig_GTEx_eQTL/eqtl_mapping/bed"
EXPRESSION_SUFFIX=".expr_tmm_inv.bed.gz"

# Covariates: 5 or 10 expression PCs + 10 PEER factors.
DIR_COVARIATES="/path/to/Pig_GTEx_eQTL/eqtl_mapping/covar_5or10pc10peer"
COVARIATES_SUFFIX=".covariates.txt"

# PLINK 2 genotype prefix, WITHOUT the .pgen/.pvar/.psam (or .bed/.bim/.fam)
# extension. Genotypes were filtered to MAF >= 0.05 and MAC >= 6.
DIR_GENOTYPE="/path/to/Pig_GTEx_eQTL/genotypes/filtered_plink2_format"
GENOTYPE_SUFFIX=".filtered_maf0.05_mac6"

# Output directory (relative to WORK_DIR).
DIR_OUTPUT="output_celltype_maf0.05_Plink2"

# MAF threshold for variants tested in the interaction model.
MAF_THRESHOLD_INTERACTION=0.05

# -----------------------------------------------------------------------------
# Tissue list. THE ORDER MATTERS: the position in this array is the array-job
# task index used to select a tissue (0-based).
# -----------------------------------------------------------------------------
TISSUES=(
    Adipose Artery Blastocyst Blastomere Blood Brain Cartilage Colon Duodenum
    Embryo Fetal_thymus Frontal_cortex Heart Hypothalamus Ileum Jejunum Kidney
    Large_intestine Liver Lung Lymph_node Macrophage Milk Morula Muscle Oocyte
    Ovary Pituitary Placenta Small_intestine Spleen Synovial_membrane Testis
    Uterus
)
N_TISSUES=${#TISSUES[@]}

# -----------------------------------------------------------------------------
# Resolve and validate the tissue index supplied on the command line
# -----------------------------------------------------------------------------
TISSUE_INDEX="${1:-}"

if [[ -z "${TISSUE_INDEX}" ]]; then
    echo "ERROR: no tissue index supplied." >&2
    echo "Usage: bash $(basename "$0") <TISSUE_INDEX>   # 0..$((N_TISSUES - 1))" >&2
    exit 1
fi

if ! [[ "${TISSUE_INDEX}" =~ ^[0-9]+$ ]] || (( TISSUE_INDEX >= N_TISSUES )); then
    echo "ERROR: tissue index '${TISSUE_INDEX}' is out of range (expected 0..$((N_TISSUES - 1)))." >&2
    exit 1
fi

TISSUE="${TISSUES[$TISSUE_INDEX]}"

# -----------------------------------------------------------------------------
# Move into the working directory and resolve all input paths
# -----------------------------------------------------------------------------
cd "${WORK_DIR}" || { echo "ERROR: cannot change directory to ${WORK_DIR}." >&2; exit 1; }

mkdir -p "${DIR_OUTPUT}/${TISSUE}"

EXPRESSION_BED="${DIR_EXPRESSION}/${TISSUE}${EXPRESSION_SUFFIX}"
COVARIATES_FILE="${DIR_COVARIATES}/${TISSUE}${COVARIATES_SUFFIX}"
PLINK_PREFIX="${DIR_GENOTYPE}/${TISSUE}${GENOTYPE_SUFFIX}"

# Sanity checks so a mis-typed path fails immediately instead of mid-array-job.
for f in "${EXPRESSION_BED}" "${COVARIATES_FILE}"; do
    if [[ ! -f "${f}" ]]; then
        echo "ERROR: input file not found: ${f}" >&2
        exit 1
    fi
done
if [[ ! -f "${PLINK_PREFIX}.pgen" && ! -f "${PLINK_PREFIX}.bed" ]]; then
    echo "ERROR: no PLINK genotype files found for prefix: ${PLINK_PREFIX}" >&2
    exit 1
fi

# -----------------------------------------------------------------------------
# Collect one interaction-term file per cell type of this tissue
# -----------------------------------------------------------------------------
shopt -s nullglob
INTERACTION_FILES=("${DIR_INTERACTION}/${TISSUE}".interactions_*.txt)
shopt -u nullglob

if (( ${#INTERACTION_FILES[@]} == 0 )); then
    echo "ERROR: no interaction-term files matching '${DIR_INTERACTION}/${TISSUE}.interactions_*.txt'." >&2
    exit 1
fi

echo "[$(date '+%F %T')] Tissue ${TISSUE} (index ${TISSUE_INDEX}): ${#INTERACTION_FILES[@]} cell type(s) to process."

# -----------------------------------------------------------------------------
# Run tensorQTL in cis-nominal interaction mode, once per cell type
# -----------------------------------------------------------------------------
for INTERACTION_FILE in "${INTERACTION_FILES[@]}"; do

    # Derive the cell-type label from the file name:
    #     .../${tissue}.interactions_${celltype}.txt  ->  ${celltype}
    CELLTYPE="$(basename "${INTERACTION_FILE}")"
    CELLTYPE="${CELLTYPE#"${TISSUE}".interactions_}"
    CELLTYPE="${CELLTYPE%.txt}"

    # tensorQTL appends its own suffixes to this prefix.
    PREFIX="${DIR_OUTPUT}/${TISSUE}/${TISSUE}.interactions_${CELLTYPE}"

    echo "[$(date '+%F %T')] Running tensorQTL: ${TISSUE} | ${CELLTYPE}"

    python3 -m tensorqtl "${PLINK_PREFIX}" "${EXPRESSION_BED}" "${PREFIX}" \
        --covariates "${COVARIATES_FILE}" \
        --interaction "${INTERACTION_FILE}" \
        --maf_threshold_interaction "${MAF_THRESHOLD_INTERACTION}" \
        --best_only \
        --mode cis_nominal

done

echo "[$(date '+%F %T')] Done: tissue ${TISSUE} (index ${TISSUE_INDEX})."
